name: SkinOverlay
version: 1.7.1
main: dev.piglin.skinoverlay.SkinOverlay
api-version: 1.19
authors: [ Iaiao ]
permissions:
  skinoverlay.wear:
    default: true
    description: /wear
  skinoverlay.wear.others:
    default: op
    description: /wear <player> <...>
  skinoverlay.wear.url:
    default: true
    description: /wear <url>
  skinoverlay.clear:
    default: true
    description: /wear clear