name: SkinOverlay
version: ${project.version}
main: dev.piglin.skinoverlay.SkinOverlay
api-version: 1.17
authors: [ Iaiao ]
website: https://piglin.dev/
commands: 
  wear:
    permission: skinoverlay.wear
    usage: /<command> <overlay name>
permissions: 
  skinoverlay.wear:
    default: true
    description: /wear
  skinoverlay.wear.others:
    default: op
    description: /wear <player>
  skinoverlay.wear.url:
    default: true
    description: /wear <url>