name: SkinOverlay
version: 2.0.0
main: dev.arubik.skinoverlay.SkinOverlay
api-version: 1.21
api: 1-21
authors: [ Iaiao, ArubikU ]
permissions:
  skinoverlay.wear:
    default: true
    description: /wear
  skinoverlay.wear.others:
    default: op
    description: /wear <player> <...>
  skinoverlay.wear.url:
    default: true
    description: /wear <url>
  skinoverlay.clear:
    default: true
    description: /wear clear