name: SkinOverlay
version: 1.7.0
main: dev.piglin.skinoverlay.SkinOverlay
api-version: 1.19
authors: [ Iaiao ]
commands:
  wear:
    permission: skinoverlay.wear
    usage: /<command> <overlay name>
permissions:
  skinoverlay.wear:
    default: true
    description: /wear
  skinoverlay.wear.others:
    default: op
    description: /wear <player>
  skinoverlay.wear.url:
    default: true
    description: /wear <url>